### PR TITLE
Use own toLowerCamel for arguments since ID must be id not iD.

### PR DESCRIPTION
**Pull request by mattn**
A consecutive words containing common words sometimes have to be converted with own case independently.

### CODE REVIEW

**Comment by mattn** [comment]
Please take a look carefully since I'm not sure this toLowerCase support all of case we want.

**Comment by moznion** [comment]
Thank you for contributing.

The idea seems really good. However, I'm considering whether this library should have such function inside.
I suppose there are following three ways to format the string case precisely:

- merge this pull-request
- extract changes of this pull-request to an external package and use it
- use `golint` output
  - IIRC, golint shows a warning like: `main.go:5:6: func useHttp should be useHTTP`
  - if could, how about reusing golint's code?

What do you think? Just for the record, I think this pull-request looks good to me!

**Comment by moznion** [comment]
If we could use golint auto-correction, it would be easy to support...
https://github.com/golang/lint/issues/214

**Comment by mattn** [comment]
Thanks your pointing the URL. I'll look into it in later. :+1:

**Comment by moznion** [comment]
Hello

I've implemented the go-lint fixing feature for this purpose, but I'm not sure when will it be merged (possibly never): https://github.com/golang/lint/pull/476
So now, I'm welcome to merge this commit. I'll do that.

@kovetskiy 
By the way, are you interested in to be a co-maintainer of this project?  If so, I'm very happy.

**Comment by kovetskiy** [comment]
Hi,
> By the way, are you interested in to be a co-maintainer of this project? If so, I'm very happy.
@moznion sure, it will be much easier.

**Comment by moznion** [comment]
@mattn thank you for your pull-request! I've just merged that with fixing conflicts.

**Comment by moznion** [comment]
@kovetskiy thank you for your cooperation. I've just sent an invitation for that.
And I'm reviewing #3 now, I'm sorry for the delayed response.

**Pull request merged**
